stages:
  - build
  - test
  - release


## Making sure that the composer cache folder is the one we have in the CI cache
before_script:
  - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache

unit_tests_7.0:
  cache:
    key: "laravel-tus-upload"
    paths:
    - .composer-cache/
  image: "docker.klink.asia/main/docker-php:7.0"
  tags:
    - docker
  stage: test
  script:
    - composer install --prefer-dist
    - ./vendor/bin/phpunit



## Javascript unit tests
js_tests:
  image: node:8
  stage: test
  cache:
    key: "laravel-tus-upload-js-node8"
    paths:
    - .npm-cache
  before_script:
    - npm config set cache .npm-cache
    - npm install -q
  script:
   - npm run test
  tags:
    - docker
